version: '3.2'
services:
  fast-go:
    container_name:{{.app_name}}
    restart: always
    ports: 
     - 19098:19098
    image: image_name
    network_mode: "host"
    logging:
      options:
        max-size: "1g"
        max-file: "2"
    volumes:
      - ./config.toml:/root/config.toml
      - ./log:/root/log
    entrypoint:
      - {{.app_name}}
      - server
